apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service
  namespace: default
  labels:
    app: movie-info-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-info-service
  template:
    metadata:
      labels:
        app: movie-info-service
    spec:
      containers:
      - name: movie-info-service
        image: <your-docker-registry>/movie-info-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DATABASE_URL
          value: "<database-url>"
        - name: DATABASE_USER
          value: "<database-user>"
        - name: DATABASE_PASSWORD
          value: "<database-password>"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
