apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
        - name: movie-catalog-service
          image: saikiran8050/movie-catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DISCOVERY_SERVER_URL
              value: "http://discovery-server:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  namespace: microservices
spec:
  selector:
    app: movie-catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
