apiVersion: v1
kind: Service
metadata:
  name: ratings-service
spec:
  type: LoadBalancer  # Can be NodePort or ClusterIP based on your needs
  selector:
    app: ratings-service
  ports:
    - protocol: TCP
      port: 80      # Port on which the service will be exposed
      targetPort: 8080  # Port on which the container is listening
